---
deployment:
  tasks:
    # 1️⃣ Set your LIVE website folder path
    - export DEPLOYPATH=/home2/yustamco/public_html/muslimshelpinghumanity.org.ng/

    # 2️⃣ Create the deploy path if it doesn't exist
    - /bin/mkdir -p $DEPLOYPATH

    # 3️⃣ Copy files to the live site (safe alternative to rsync)
    - /bin/cp -R ./* $DEPLOYPATH

    # 4️⃣ Fix permissions
    - /bin/find $DEPLOYPATH -type d -exec chmod 755 {} \;
    - /bin/find $DEPLOYPATH -type f -exec chmod 644 {} \;
